[package]
name = "polyxml-python"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Python bindings for PolyXML (polyxml-core)"

[lib]
name = "_polyxml"
crate-type = ["cdylib"]

[dependencies]
polyxml = { path = "../polyxml-core" }
pyo3 = { version = "0.22", features = ["abi3-py312", "extension-module"] }
quick-xml = { version = "0.36" }
lexical-core = "1.0"
smallvec = "1.16"
