#!/usr/bin/env python3
"""Generate benches/support/tag_dispatch_fixtures.rs.

The Criterion suite in benches/tag_dispatch.rs compares three tag-dispatch
strategies (string `match`, runtime HashMap, compile-time phf::Map) at the
schema scale tiers. The per-tier tag lists and match
functions are too large to hand-maintain, so they are generated here with a
fixed seed and committed alongside the bench.

Usage:
    python3 scripts/gen_tag_dispatch_fixtures.py
"""

from __future__ import annotations

import random
from pathlib import Path

OUT = (
    Path(__file__).resolve().parents[1]
    / "crates"
    / "polyxml-core"
    / "benches"
    / "support"
    / "tag_dispatch_fixtures.rs"
)

# Scale tiers: small, medium, large, and extra-large.
# Both ends of the large range are sampled so the match->phf crossover (if any)
# is measured rather than extrapolated.
TIERS = [16, 120, 600, 1500]
SEED = 490490

# Realistic enterprise-tag vocabulary; lengths ~12-45 bytes so LLVM's
# length-bucketed memcmp chains are not artificially favored.
WORDS = [
    "Settlement",
    "Instruction",
    "Party",
    "Account",
    "Amount",
    "Currency",
    "ValueDate",
    "Reference",
    "Status",
    "Identification",
    "Transmission",
    "Reconciliation",
    "Clearing",
    "Margin",
    "Collateral",
    "Beneficiary",
    "Remittance",
    "Routing",
    "Authentication",
    "Sequence",
    "Version",
    "Channel",
    "Priority",
    "Category",
    "Adjustment",
    "Position",
    "Statement",
    "Transaction",
]
SUFFIXES = [
    "",
    "",
    "Code",
    "Type",
    "Flag",
    "Indicator",
    "Date",
    "Id",
    "Count",
    "1",
    "2",
    "Sub",
    "Report",
]


def make_tags(n: int, seed: int) -> list[str]:
    rng = random.Random(seed)
    # Two-word composition keeps the space (28*28*13 = 10k+) well above the
    # largest tier; the guard turns any future space shortfall into a clear
    # error instead of an infinite loop.
    attempts = 0
    tags: set[str] = set()
    while len(tags) < n:
        tags.add(rng.choice(WORDS) + rng.choice(WORDS) + rng.choice(SUFFIXES))
        attempts += 1
        if attempts > n * 100:
            raise RuntimeError(f"tag space too small for tier {n} ({len(tags)} unique)")
    return sorted(tags)


def emit(tier: int, tags: list[str], out: list[str]) -> None:
    n = len(tags)
    out.append(
        f"// --- Tier {n} ({'small' if n <= 25 else 'medium' if n <= 150 else 'large'}) ---"
    )
    out.append(f"pub const TAGS_{n}: [&str; {n}] = [")
    for t in tags:
        out.append(f'    "{t}",')
    out.append("];")
    out.append("")
    out.append(f"pub fn match_dispatch_{n}(tag: &str) -> Option<u32> {{")
    out.append("    match tag {")
    for i, t in enumerate(tags):
        out.append(f'        "{t}" => Some({i}),')
    out.append("        _ => None,")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append(f"pub static PHF_{n}: phf::Map<&'static str, u32> = phf::phf_map! {{")
    for i, t in enumerate(tags):
        out.append(f'    "{t}" => {i}u32,')
    out.append("};")
    out.append("")


def main() -> None:
    header = [
        "// GENERATED by scripts/gen_tag_dispatch_fixtures.py — do not edit.",
        "// Tag lists, string-match baselines, and phf tables for the",
        "// tag_dispatch Criterion bench. Regenerate with:",
        "//     python3 scripts/gen_tag_dispatch_fixtures.py",
        "",
        "#![allow(clippy::all)]",
        "",
    ]
    out = list(header)
    for tier in TIERS:
        emit(tier, make_tags(tier, SEED + tier), out)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({len(out)} lines)")


if __name__ == "__main__":
    main()
